services:
  redis:
    container_name: redis
    image: redis
    environment:
      - save=60 1000
      - requirepass=1234
      - appendonly=yes
    volumes:
      - /c/kimson/redis/redis.conf:/etc/redis/redis.conf
      - /c/kimson/redis_data:/data
    restart: always
    ports:
      - 6379:6379
    command: ['redis-server', '/etc/redis/redis.conf']
